services:
  home-office-database:
    build:
      context: ./home-office/database
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
    container_name: home-office-database
    ports:
      - 5555:5432
  home-office-service:
    build:
      context: ../home-office
      dockerfile: ../infrastructure/home-office/service/Dockerfile
    environment:
      db_username:
      db_password:
    container_name: home-office-service
    ports:
      - 8080:8080
    depends_on:
      - home-office-database
  cowshed-database:
    build:
      context: ./cowshed/database
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
    container_name: cowshed-database
    ports:
      - 5565:5432
  cowshed-service:
    build:
      context: ../cowshed
      dockerfile: ../infrastructure/cowshed/service/Dockerfile
    environment:
      db_username:
      db_password:
    container_name: cowshed-service
    ports:
      - 8081:8081
    depends_on:
      - cowshed-database