name: github-actions-grange
on:
  pull_request:
    paths:
      - 'home-office/**'
jobs:
  home-office:
    name: "home-office build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "setup jdk 21"
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew
      - name: "Build with Gradle"
        run: ./gradlew home-office:build
  cowshed:
    name: "cowshed build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "setup jdk 21"
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew
      - name: "Build with Gradle"
        run: ./gradlew cowshed:build
  henhouse:
    name: "henhouse build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "setup jdk 21"
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew
      - name: "Build with Gradle"
        run: ./gradlew henhouse:build
  cheese-factory:
    name: "cheese-factory build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "setup jdk 21"
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew
      - name: "Build with Gradle"
        run: ./gradlew cheese-factory:build
  guardhouse:
    name: "guardhouse build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "setup jdk 21"
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: "Change wrapper permissions"
        run: chmod +x ./gradlew
      - name: "Build with Gradle"
        run: ./gradlew guardhouse:build